### ISSUE TITLE
🔷 [EPIC] New wallet.near.org Landing Page

### ISSUE THREAD

**Issue by trechriron** [near/wallet-experience#1]
### Description

Repurpose wallet.near.org from NEAR wallet to a wallet info clearing house that shows NEAR users all the available wallets in the ecosystem.

```[tasklist]
### Related Issues
- [ ] https://github.com/near/wallet-experience/issues/11
- [ ] https://github.com/near/wallet-experience/issues/13
- [ ] https://github.com/near/wallet-experience/issues/12
- [ ] https://github.com/near/wallet-experience/issues/14
- [ ] https://github.com/near/wallet-experience/issues/15
- [ ] https://github.com/near/wallet-experience/issues/16
```

**Comment by trechriron** [comment]
Not doing. New DiscoverBOS page in progress to replace Awesome NEAR.
